name: AdvancedArmorStands
version: '${project.version}'
main: me.parsa.aas.AdvancedArmorStands
softdepend: [PlaceholderAPI]
permissions:
  advanced-armorstands.admin:
    description: Admin access for aas
    default: op
commands:
  as:
    aliases:
      - advancedarmorstands
      - aas
    usage: /as