name: AdvancedArmorStands
version: '${project.version}'
api-version: '1.13'
main: com.parsa3323.aas.AdvancedArmorStands
softdepend: [PlaceholderAPI]
permissions:
  advanced-armorstands.admin:
    description: Admin access for AdvancedArmorStands
    default: op
commands:
  as:
    aliases:
      - advancedarmorstands
      - aas
    usage: /as