name: AdvancedArmorStands
version: '${project.version}'
api-version: '1.13'
main: com.parsa3323.aas.AdvancedArmorStands
description: 'Top #1 armor stand plugin'
author: Parsa3323
softdepend: [PlaceholderAPI]
permissions:
  advanced-armorstands.admin:
    description: Admin access for AdvancedArmorStands
    default: op
commands:
  as:
    aliases:
      - advancedarmorstands
      - aas
      - aa
    usage: /as