name: Update Contributor Photos
on:
  schedule:
    - cron: '0 0 * * *'  # Daily update
  workflow_dispatch:     # Manual trigger option

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate contributor photos
        uses: jasonlong/gha-contributors-svg@main
        with:
          repo: "Parsa3323/AdvancedArmorStands"  # Replace with your repo
          width: 800                       # SVG width
          columns: 10                      # Photos per row
          size: 60                         # Photo size in px
          radius: 30                       # Roundness (30 for circle)
          output: contributors.svg         # Output file

      - name: Update README
        run: |
          # Clear old section
          sed -i '/<!-- CONTRIBUTORS-START -->/,/<!-- CONTRIBUTORS-END -->/d' README.md
          # Add new section
          echo '<!-- CONTRIBUTORS-START -->' >> README.md
          echo '## Contributors' >> README.md
          echo '![Contributors](data:image/svg+xml;base64,'$(base64 -w 0 contributors.svg)')' >> README.md
          echo '<!-- CONTRIBUTORS-END -->' >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update contributor photos"
          git push