name: Update Contributor Avatars
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-avatars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate contributor avatars
        uses: varunsridharan/action-contributors@1.2.0
        with:
          REPO: "Parsa3323/AdvancedArmorStands"  # Replace with your repo
          AVATAR_TYPE: "round"  # or "square"
          AVATAR_SIZE: "60"    # pixel size
          COLUMNS: "10"         # avatars per row
          COMMIT: "true"        # auto-commit changes
          COMMIT_MESSAGE: "chore: update contributor avatars"
          GITHUB_TOKEN: ${{ github.token }}