name: Publish API to GitHub Packages

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: github

      - name: Setup Maven authentication
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>Parsa3323</username>
                <password>\${{ secrets.REPO_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build and deploy
        run: mvn -B clean deploy --settings ~/.m2/settings.xml
        env:
          GITHUB_TOKEN: \${{ secrets.REPO_TOKEN }}