name: Publish to GitHub Packages

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'EOF'
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.REPO_TOKEN }}</password>
                <configuration>
                  <httpHeaders>
                    <property>
                      <name>Authorization</name>
                      <value>token ${{ secrets.REPO_TOKEN }}</value>
                    </property>
                  </httpHeaders>
                </configuration>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build and deploy
        run: |
          mvn -B clean install
          mvn -B deploy \
            -DaltDeploymentRepository=github::https://maven.pkg.github.com/Parsa3323/AdvancedArmorStands