name: Resource Validation

on:
  pull_request_target:
    branches: ["*"]

jobs:
  validate-resources:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: pr-code

      - name: Find resource folders
        id: find-resources
        run: |
          echo "Checking these resource folders:"
          find pr-code -type d -path "*/src/main/resources" | tee resource_dirs.txt
          echo "::set-output name=resource_dirs::$(cat resource_dirs.txt | jq -R -s -c 'split("\n")[:-1]')"

      - name: Validate resources
        run: |
          echo "Found resource directories:"
          echo '${{ steps.find-resources.outputs.resource_dirs }}' | jq -r '.[]'
          
          # Basic validation - just check plugin.yml exists
          for dir in $(echo '${{ steps.find-resources.outputs.resource_dirs }}' | jq -r '.[]'); do
            if [ ! -f "$dir/plugin.yml" ]; then
              echo "::error::Missing plugin.yml in $dir"
              echo "validation_failed=true" >> $GITHUB_ENV
            fi
          done

      - name: Post validation result
        if: ${{ env.validation_failed == 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Resource validation failed: Missing plugin.yml in some resource folders'
            })
            core.setFailed('Resource validation failed')